
### nuevo usuario
POST http://localhost:8000/auth/register
Content-Type: application/json

{
  "username":"david",
  "password":"1"
}

### iniciar sesión
POST http://localhost:8000/auth/login
Content-Type: application/json

{
  "username":"hola jajajaja",
  "password":"1234569"
}

###
GET http://localhost:8000/user
token: {{token}}
