
### crear nueva categoria
POST http://localhost:8000/category
Content-Type: application/json
token: {{token}}

{
  "name": "categoria2",
  "description": "Descripcion de la nueva categoria"
}

### obtener todas las categorías
GET http://localhost:8000/category
token: {{token}}

### obtener categoria por ID
GET http://localhost:8000/category/3
token: {{token}}

### actualizar categoria
PATCH http://localhost:8000/category/3
Content-Type: application/json
token: {{token}}

{
  "name": "categoria 3 editada"
}

### eliminar categoria
DELETE http://localhost:8000/category/3
token: {{token}}
