
### crear un producto
POST http://localhost:8000/product
Content-Type: application/json
token: {{token}}

{
  "name": "Producto 3",
  "categoryId": 1, 
  "supplierId": 1,
  "price": 10.99,
  "stock": 100
}

### obtener todos los productos
GET http://localhost:8000/product
token: {{token}}

### obtener producto por ID
GET http://localhost:8000/product/2
token: {{token}}

### actualizar producto
PATCH http://localhost:8000/product/2
Content-Type: application/json
token: {{token}}

{
  "stock": 2
}

### eliminar producto
DELETE http://localhost:8000/product/2
token: {{token}}
