
### crear un producto
POST http://localhost:8000/product/
Content-Type: application/json
token: {{token}}

{
  "name": "new",
  "categoryId": 1, 
  "supplierId": 1,
  "price": 1,
  "stock": 100
}

### obtener todos los productos
GET http://localhost:8000/product
token: {{token}}

### obtener producto por ID
GET http://localhost:8000/product/1
token: {{token}}

### actualizar producto
PATCH http://localhost:8000/product/1
Content-Type: application/json
token: {{token}}

{
  "name":123
}

### eliminar producto
DELETE http://localhost:8000/product/2
token: {{token}}
