
### crear venta (requiere autenticación)
POST http://localhost:8000/venta
Content-Type: application/json
token: {{token}}

{
  "productId": 1,
  "quantity": 10
}

### obtener ventas
GET http://localhost:8000/venta
token: {{token}}
